home:
  alias: '/shop'

pages:
  theme: antimatter
  process:
    markdown: true
    twig: false
  events:
    page: true
    twig: true

cache:
  enabled: true
  check:
    pages: true
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

debugger:
  enabled: true
  max_depth: 10
  log:
    enabled: false
    timing: false
